name: Scrape and Send

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Update CA certificates
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        sudo update-ca-certificates
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-telegram-bot pyshorteners pymongo
    
    - name: Run script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DB_NAME: ${{ secrets.DB_NAME }}
        COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
      run: python main.py
